# Use an official Node.js runtime as a parent image
FROM node:16

# Set the working directory in the container
WORKDIR /app

# Install Truffle globally
RUN npm install -g truffle

#copy necesary files
COPY ./blockchain/bc_migrations /app/migrations
COPY ./blockchain/truffle-config.js /app/truffle-config.js
COPY ./blockchain/contracts /app/contracts

# Expose ports if necessary (not needed in this case)
EXPOSE 8545

# Default command to run Truffle commands
CMD ["truffle"]
