# Generated by Django 4.2.15 on 2024-09-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('alias', models.CharField(max_length=10)),
                ('wins', models.PositiveIntegerField()),
                ('loses', models.PositiveIntegerField()),
                ('games_played', models.PositiveIntegerField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('intra_image', models.URLField(max_length=512)),
                ('friends', models.ManyToManyField(blank=True, to='social.user')),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
    ]
